Add missing newlines at end of files
This is a fix for the following error:

error: LF will be replaced by CRLF in Codeforces/problemset/1520/D_Same_Differences.cpp.
The file will have its original line endings in your working directory.

error: LF will be replaced by CRLF in Codeforces/problemset/1520/E_Arranging_The_Sheep.cpp.
The file will have its original line endings in your working directory.